# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='cumm_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
