# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180608_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
