# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_other_date_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-date_uploaded',)},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'ordering': ('-date_uploaded',)},
        ),
    ]
